version: "3.8"

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s

  scraper:
    build: .
    ports:
      - "3000:3000"  # Critical addition
    environment:
      - REDIS_HOST=redis
    depends_on:
      redis:
        condition: service_healthy

volumes:
  redis-data: