# version: "3.8"

# services:
#   redis:
#     image: redis:7
#     ports:
#       - "6379:6379"
#     volumes:
#       - redis-data:/data
#     healthcheck:
#       test: ["CMD", "redis-cli", "ping"]
#       interval: 5s

#   scraper:
#     build: .
#     ports:
#       - "3000:3000"  # Critical addition
#     environment:
#       - REDIS_HOST=redis
#     depends_on:
#       redis:
#         condition: service_healthy

# volumes:
#   redis-data:

version: "3.8"

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s

  browserless:
    image: ghcr.io/browserless/chromium
    ports:
      - "3001:3000"
    environment:
      - TOKEN=72soy5TgTCncP1HkdVyd06DVdLEVwVFceVYqIuiVj1EpIUiR
      - CONCURRENT=10
      - TIMEOUT=-1
    restart: unless-stopped
    shm_size: "1gb"

  scraper:
    build: .
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - BROWSERLESS_TOKEN=72soy5TgTCncP1HkdVyd06DVdLEVwVFceVYqIuiVj1EpIUiR
      - BROWSER_WS_ENDPOINT_PRIVATE=ws://browserless.railway.internal:3001?token=72soy5TgTCncP1HkdVyd06DVdLEVwVFceVYqIuiVj1EpIUiR
      - BROWSER_WS_ENDPOINT_LOCAL=ws://localhost:3000?token=2SxiECl9q7mfgqW368f0c7e8264cc54dca4d87a30dc46cfa2
    depends_on:
      redis:
        condition: service_healthy
      browserless:
        condition: service_started

volumes:
  redis-data:
